apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-vector-scheduled
spec:
  schedule: "{{ .Values.s3.schedule }}"
  cluster:
    name: cnpg-vector
  backupOwnerReference: self

