apiVersion: v2
name: cnpg-vector
description: CloudNativePG + PostgreSQL 16 + pgvector + PgBouncer + S3 Backups
type: application
version: 0.1.0
appVersion: "1.0"

  #dependencies:
  #- name: cloudnative-pg
  # repository: https://cloudnative-pg.github.io/charts
  # version: "0.20.*"

